# Generated by Django 4.1.2 on 2023-03-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('preview', models.TextField()),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
